# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20161017_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('shoplist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.ShoppingList')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
    ]
