# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoppinglistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
