# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shoppinglist_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
